### ISSUE TITLE
no t printing text and not saving audio

### ISSUE THREAD

**Issue by suhana9010** [Tejas-Achar/PDF-to-AudioBooks#1]

**Comment by Tejas-Achar** [comment]
> hey am not getting text for 2 or more page pdfs.....help me



> hey am not getting text for 2 or more page pdfs.....help me

Hey,

I just tested with a multi-page sample pdf, worked fine for me. The issue that you're facing might be related to the pdf itself. Meaning the pdf might be corrupted.

**Comment by suhana9010** [comment]
got it
